### ISSUE TITLE
RawMapping possible unnecessary

### ISSUE THREAD

**Issue by deuszx** [Brushfam/openbrush-contracts#101]
`RawMapping` might be replaceable with pure ink! `Mapping` since ink! 4 . 

It seems like `RawMapping` was introduced back in ink!3 times to fix some of `ink::storage::Mapping` 's deficiencies. Now, each `Mapping` value in contract's struct will get its own and unique (within that contract's scope) key in the underlying blockchain storage while just that key will be stored in the contract struct itself. 

Looking at the code of `RawMapping::insert` and `RawMapping::get` it behaves similarly to `Mapping::insert`/`Mapping::get` - ie each entry will be stored in the enclosing contract's storage (`ink_env::set_contract_storage`) but also use its `Mapping`'s unique key - similarly to how `RawMapping` uses its `prefix`.

If that's true, I'd suggest removal of `RawMapping` and using ink's built-in `Mapping` instead - the less complex code the better.

**Comment by coreggon11** [comment]
Hi, thanks for your input. We are currently finishing a new major update of OB and also removing unnecessary code from ink! 3

**Comment by coreggon11** [comment]
Hi @deuszx , in OB we have introduced our own restricted version of `Mapping` and also a `MultiMapping` struct, and `RawMapping` is used to ease the implementation of these structs.

**Comment by deuszx** [comment]
Hey @coreggon11 , can you give an example where OB's `Mapping` is superior to ink! ?
