### ISSUE TITLE
Cargo clippy raises an error for the macro  #[openbrush::trait_definition]

### ISSUE THREAD

**Issue by GuiGou12358** [Brushfam/openbrush-contracts#111]
Hello,

cargo clippy raises the following error:

3 | #[openbrush::trait_definition]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#inline_fn_without_body
  = note: #[deny(clippy::inline_fn_without_body)] on by default
  = note: this error originates in the attribute macro openbrush::trait_definition (in Nightly builds, run with -Z macro-backtrace for more info) 

Please could you have a look and fix the issue?

**Comment by coreggon11** [comment]
Hi @GuiGou12358 , this issue will be fixed in the new release

**Comment by GuiGou12358** [comment]
Hi @coreggon11 , perfect, thank you!
