### ISSUE TITLE
openbrush trait implementation error: "not all trait items implemented, missing: `__ink_TraitInfo`"

### ISSUE THREAD

**Issue by wolfwarrier14** [Brushfam/openbrush-contracts#33]
I wrote trait using #[openbrush::trait_definition] and tried to implement in contract.
But it cause error 
"not all trait items implemented, missing: `__ink_TraitInfo`, `rampAOutput`
missing `__ink_TraitInfo`, `rampAOutput` in implementation"

Trait Definition

    
    #[openbrush::wrapper]
    pub type KaglaAdminRef = dyn KaglaAdmin;
    
    #[openbrush::trait_definition]
    pub trait KaglaAdmin {
        #[ink(message)]
        fn ramp_a(&mut self, _future_a: u128, _future_time: u128) -> Result<(), KaglaAdminError>;
    }

    pub type Result<T, KaglaAdminError> = core::result::Result<T, KaglaAdminError>;

    #[derive(Debug, PartialEq, Eq, scale::Encode, scale::Decode)]
    #[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]
    pub enum KaglaAdminError {
        PermissionDenied,
    }

And this is the contract implementation

    #![cfg_attr(not(feature = "std"), no_std)]
    #![feature(min_specialization)]

    #[openbrush::contract]
    pub mod _3pool {
        #[ink(storage)]
        #[derive(Default, Storage)]
        pub struct StableSwap3PoolContract {
            #[storage_field]
            admin: KaglaAdminData,
        }

        impl KaglaAdmin for StableSwap3PoolContract {
            fn ramp_a(&mut self, _future_a: u128, _future_time: u128) -> Result<(), KaglaAdminError> {
                Ok(())
            }
        }
    }

**Comment by michaelassaf** [comment]
Getting the same issue from the ink pausable contract example.

**Comment by coreggon11** [comment]
You are missing `#[ink(message)]` attribute in your impl

**Comment by michaelassaf** [comment]
This solved the issue, thank you!
