### ISSUE TITLE
Delegate calls fix

### ISSUE THREAD

**Issue by Artemka374** [Brushfam/openbrush-contracts#36]
Right now delegate calls can't work as they were before due to latest ink! changes.
As was mentioned in [this issue](https://github.com/paritytech/ink/issues/1388), the problem is in initializing storage, so, we have the following possible options of making everything work:
* Using an empty ink(storage) struct and wrapping the main storage into another structure with initializing in `Storable::decode` method
* We can implement custom `Storable::decode` method, so every struct will be extracted from storage by it's own storage key and initialized if it is not, like it was implemented [here](https://github.com/727-Ventures/openbrush-contracts/pull/32), but we have a problem, that we can reimplement `encode` method for structs to be set to storage by theirs storage key by default, so we will need to manually flush every such struct in storage.
* Using `Lazy` for every such struct, but the downsides of this approach is that it will change the approach of working with any contract a lot

The best solution for this problem will be implementing something like [this](https://github.com/paritytech/ink/issues/1388#issuecomment-1259595641) in ink! itself.

**Comment by PierreOssun** [comment]
@Artemka374 Will this be fixed by [#76(]https://github.com/Brushfam/openbrush-contracts/pull/76) ?
Any update on when can we have diamond contracts back ?
