### ISSUE TITLE
e2e testing

### ISSUE THREAD

**Issue by stillonearth** [Brushfam/openbrush-contracts#41]
[Ink 4.0](https://github.com/paritytech/ink/releases/tag/v4.0.0) introduced e2e testing. How do I leverage this for [example project structure](https://github.com/Brushfam/openbrush-contracts/tree/main/example_project_structure)?

**Comment by stillonearth** [comment]
Ink 4.0 allows to instantiate contracts on a chain with 

```rust
let constructor = MyContractRef::new_default();
            let contract_acc_id = client
                .instantiate("contract", &ink_e2e::alice(), constructor, 0, None)
                .await
                .expect("instantiate failed")
                .account_id;
```

The problems is that contract MyContractRef can't be imported when wrapped in #[openbrush::contract]

**Comment by stillonearth** [comment]
So, for anyone experiencing the same problems

1. Change crate-type in Cargo.toml
```crate-type = ["cdylib", "rlib"]```
2. Import a contract with ```contract = { path = "../contract", features = ["ink-as-dependency"] }```

**Comment by stillonearth** [comment]
Still i'm confused how to get wrapped ContractRef to instantiate it withing e2e test

```rust
#[cfg(all(test, feature = "e2e-tests"))]
mod e2e_tests {
    use super::*;
    use ink_e2e::build_message;
    use my_contract::contract_metadata::SomeContract;
    type E2EResult<T> = std::result::Result<T, Box<dyn std::error::Error>>;

    #[ink_e2e::test]
    async fn minting_works(mut client: ink_e2e::Client<C, E>) -> E2EResult<()> {
        let constructor = SomeContractRef::new();
        // (!) SomeContractRef doesn't have `new` here
        // In flipper example it does work
        // https://github.com/paritytech/ink-examples/blob/main/flipper/lib.rs
        let contract_acc_id = client
            .instantiate("some_contract", &ink_e2e::alice(), constructor, 0, None)
            .await
            .expect("instantiate failed")
            .account_id;

        Ok(())
    }
}
```

**Comment by varex83** [comment]
Hello @stillonearth , we are working on integrating the ink-e2e framework into openbrush! Feel free to take a look at the PR https://github.com/Brushfam/openbrush-contracts/pull/44

**Comment by stillonearth** [comment]
I'm using #44 code base now, but it's still unclear how to refer contract references for an example structure.

If I have a contract **A** constructor taking a contract **B** address on chain, then I need to instantiate **B** somewhere in a test. The question still remain how do I get **BRef** in **A** suit.
