### ISSUE TITLE
OpenBrush x Stable Rust

### ISSUE THREAD

**Issue by coreggon11** [Brushfam/openbrush-contracts#58]
rustc 1.71 introduced some changes to min specialization

https://github.com/rust-lang/rust/pull/111252

We will remove min_specialization altogether, so we will no longer depend on nightly features, as they may introduce breaking changes to a stable product. However, this would remove some of OpenBrush's unique features, which must be implemented differently.

TODO:
- [x] Remove min specialization
- [x] Update OpenBrush to use new trait system 
- [x] new macro to implement all needed traits
- [x] Examples building
- [X] Tests working 

Implemented in https://github.com/Brushfam/openbrush-contracts/pull/78

**Comment by coreggon11** [comment]
> Will this makes OB compile in stable ?

yes)

**Comment by deuszx** [comment]
How do you plan on supporting `default fn`s in default impls?

**Comment by Artemka374** [comment]
Hi @deuszx, we are planning to use a bit another approach for it,  with use of macros
