### ISSUE TITLE
The key argument to `openbrush::upgradeable_storage` is confusing

### ISSUE THREAD

**Issue by DamianStraszak** [Brushfam/openbrush-contracts#84]
If I understand correctly whether I use `#[openbrush::upgradeable_storage(123)]` or `#[openbrush::upgradeable_storage(500)]` makes no difference on how the data is laid out in the contract storage (everything is anyway clumped together in the `0` key). If so, then it's extremely confusing that the argument is even there.

Is my understanding correct?

**Comment by Artemka374** [comment]
Yes, you are correct, it was a change in latest ink! versions, so we will rework the macro and remove the argument, we are working on it here: https://github.com/Brushfam/openbrush-contracts/pull/49

**Comment by DamianStraszak** [comment]
Thank you. I'm eagerly waiting for the new release then :) Is there an ETA on this being released?
