### ISSUE TITLE
The usage of `non_reentrant` modifier introduces significant overhead on gas cost.

### ISSUE THREAD

**Issue by DamianStraszak** [Brushfam/openbrush-contracts#85]
As per my understanding the expected usage of the `non_reentrant` modifier is to:
- add `guard: reentrancy_guard::Data` to the contract storage
- decorate appropriate messages with `#[openbrush::modifiers(non_reentrant)]`

The issue with that seems to be that upon every entrance to a function with this decorator, the whole non-lazy part of the contract storage is flushed (as in ink! 4 the whole contract storage sits under a single key `0x00000000`). Note that this can be kilobytes or even tens of kilobytes of data, in case the contract has a large state (and yes, I know that Mappings use different keys, but apart from mappings and other `Lazy` storage, this is correct I guess). 

This overhead is not necessary and could be avoided for instance by using a `Lazy` storage for the reentrancy marker.

**Comment by DamianStraszak** [comment]
I was investigating this a little more today with https://github.com/deuszx and what we concluded is that the way the reentrancy guard is implemented is wrong and it's only a coincidence that it is not permanently corrupting the contract's storage. 

Here is an example to demonstrate what's wrong https://github.com/DamianStraszak/azero-examples/blob/main/ink/reentrancy-corrupt/lib.rs
Steps:
1. Deploy the contract
2. Call `increment` -- observe the event. The event `StorageDecodedAsGuard` will be emitted.
3. Call `increment_reentrant` -- observe the event. The event `StorageDecodedCorrectly` will be emitted. 

What this means is that upon entering a non-reentrant message, the contract's storage under key `0` is actually being corrupted, because the `non-reentrant` modifier writes the value of `guard: reentrancy_guard::Data` using a low-level call `set_contract_storage` -- see https://github.com/Brushfam/openbrush-contracts/blob/main/contracts/src/security/reentrancy_guard/mod.rs#L70

This corruption is not permanent because of how Ink! works. I.e., it flushes the contract storage upon finishing the message's execution. That's why what the non-reentrant modifier has written to key `0` is overriden, and the storage is saved from corruption. 

In contracts that don't use any low-level calls to storage, this will still work, because ink! flushes the data properly. However, the code is highly dangerous and definitely not working as intended.

**Comment by Artemka374** [comment]
Hey @DamianStraszak ! Thanks for noticing the issue, we will fix it asap.

**Comment by Artemka374** [comment]
Hey @DamianStraszak, we fixed the issue in https://github.com/Brushfam/openbrush-contracts/pull/88

**Comment by DamianStraszak** [comment]
Thanks. This looks good, although I left a small comment as a review in the PR https://github.com/Brushfam/openbrush-contracts/pull/88#pullrequestreview-1481013298

**Comment by DamianStraszak** [comment]
Another point is that this example https://github.com/Brushfam/openbrush-contracts/tree/main/examples/reentrancy_guard does not quite show the point of reentrancy guard -- as all the calls are being made with the native reentrancy protection, so one would need to `set_allow_reentry(true)` somewhere there.

**Comment by Artemka374** [comment]
https://github.com/Brushfam/openbrush-contracts/pull/108

**Comment by DamianStraszak** [comment]
Feel free to close the issue. Looks good now.
