### ISSUE TITLE
specialization impl does not specialize any associated items

### ISSUE THREAD

**Issue by fsobh** [Brushfam/openbrush-contracts#92]
I Downloaded the Very Basic PSP22 example from here : https://openbrush.brushfam.io/

I'm running the following versions of rust tools : 

- cargo-contract-contract 2.2.1-91b5a86-x86_64-unknown-linux-gnu
- rustc 1.69.0 (84c898d65 2023-04-16)
- rustup 1.26.0 (5af9b9484 2023-04-05)

I keep getting this error : 

when I try to build it using : 

`cargo +nightly contract build --release`

![image](https://github.com/Brushfam/openbrush-contracts/assets/37850797/576b0394-8ec5-4c37-beaf-4bde3e643a4c)

Is Open Brush not stable? Would it be better if I were to just use the PSP22 source code and deploy it myself?

There does not seem to be any stable means of support

**Comment by bejarano-tech** [comment]
I'm having the same issue but in my case is with PSP34

**Comment by varex83** [comment]
Hello @fsobh ! 

Yes, currently OpenBrush is not stable in the main branch, but we are practically finished stable version of it in #78 so you can already take a look / test if, and we are planning to make a release in the nearest future, that will include stabilization and upgradeable contracts!

**Comment by bejarano-tech** [comment]
> I'm having the same issue but in my case is with PSP34

Currently it works when i install and use nightly-2023-01-01 toolchain

**Comment by fsobh** [comment]
> > I'm having the same issue but in my case is with PSP34
> 
> Currently it works when i install and use nightly-2023-01-01 toolchain

I tried this and it still gave the same error. any other suggestions ?

**Comment by fsobh** [comment]
> > I'm having the same issue but in my case is with PSP34
> 
> Currently it works when i install and use nightly-2023-01-01 toolchain

This fixed my issue. Please note that you will need to restart your computer if your using WSL

**Comment by fsobh** [comment]
> 

Tries this and its still throwing the error

**Comment by fsobh** [comment]
> > I'm having the same issue but in my case is with PSP34
> 
> Currently it works when i install and use nightly-2023-01-01 toolchain

Tried this and its still throwing the error. Im running in WSL Ubuntu

**Comment by bejarano-tech** [comment]
> > > I'm having the same issue but in my case is with PSP34
> > 
> > 
> > Currently it works when i install and use nightly-2023-01-01 toolchain
> 
> Tried this and its still throwing the error. Im running in WSL Ubuntu

To build it i called `cargo +nightly-2023-01-01 contract build --release`, how are you calling to compile?

**Comment by fsobh** [comment]
> > > > I'm having the same issue but in my case is with PSP34
> > > 
> > > 
> > > Currently it works when i install and use nightly-2023-01-01 toolchain
> > 
> > 
> > Tried this and its still throwing the error. Im running in WSL Ubuntu
> 
> To build it i called `cargo +nightly-2023-01-01 contract build --release`, how are you calling to compile?

I was using : `cargo +nightly contract build --release`

After running : `cargo +nightly-2023-01-01 contract build --release`
I'm getting : ERROR: Expected '/home/fk/proj/token/psp22/target/ink/wasm32-unknown-unknown/release/my_psp22.wasm' to be generated by build

**Comment by fsobh** [comment]
> > > > > I'm having the same issue but in my case is with PSP34
> > > > 
> > > > 
> > > > Currently it works when i install and use nightly-2023-01-01 toolchain
> > > 
> > > 
> > > Tried this and its still throwing the error. Im running in WSL Ubuntu
> > 
> > 
> > To build it i called `cargo +nightly-2023-01-01 contract build --release`, how are you calling to compile?
> 
> I was using : `cargo +nightly contract build --release`
> 
> After running : `cargo +nightly-2023-01-01 contract build --release` I'm getting : ERROR: Expected '/home/fk/proj/token/psp22/target/ink/wasm32-unknown-unknown/release/my_psp22.wasm' to be generated by build

Never mind, After running `cargo clean`, It worked. Thank you so much for the help. been dealing with this for the past week
